import type { Brand, FlaggedPost } from "./types";

// Fixtures copied from real mx_flagged_interim rows (2026-08-10) so the UI can
// be developed and eyeballed without a session. One row is altered to exercise
// the assisted state, which has no live example yet.
export const MOCK_FLAGGED: FlaggedPost[] = [
  {
    external_id: "mock-dttr-104",
    brand_name: "Dance to the Radio",
    brand_type: "artist",
    owner: "Sam",
    network: "instagram",
    content_type: "posts",
    caption: "Ten years of DTTR — the story so far, in one carousel.",
    permalink: "https://www.instagram.com/p/example1/",
    thumbnail_url: null,
    published_at: "2025-11-04",
    age_days: 279,
    views: 135248,
    median_views: 1294,
    views_multiple: 104.5,
    engagement_pct: 4.1,
    skip_rate: null,
    sample_size: 20,
    assisted_from: null,
    assist_kinds: null,
    is_assisted: false,
    avg_watch_seconds: null,
  },
  {
    external_id: "mock-lobjectif-61",
    brand_name: "L'objectif",
    brand_type: "artist",
    owner: "Sam",
    network: "tiktok",
    content_type: "posts",
    caption: "new single out friday. this one's different.",
    permalink: "https://www.tiktok.com/@example/video/1",
    thumbnail_url: null,
    published_at: "2026-07-28",
    age_days: 13,
    views: 43999,
    median_views: 717.5,
    views_multiple: 61.3,
    engagement_pct: 7.9,
    skip_rate: null,
    sample_size: 20,
    assisted_from: null,
    assist_kinds: null,
    is_assisted: false,
    avg_watch_seconds: null,
  },
  {
    external_id: "mock-dttr-reel",
    brand_name: "Dance to the Radio",
    brand_type: "artist",
    owner: "Sam",
    network: "instagram",
    content_type: "reels",
    caption: "Behind the mix: how the outro came together",
    permalink: "https://www.instagram.com/reel/example2/",
    thumbnail_url: null,
    published_at: "2026-02-26",
    age_days: 165,
    views: 9060,
    median_views: 1019,
    views_multiple: 8.9,
    engagement_pct: 3.2,
    skip_rate: 66.4,
    sample_size: 18,
    assisted_from: null,
    assist_kinds: null,
    is_assisted: false,
    avg_watch_seconds: 6.4,
  },
  {
    external_id: "mock-twin-assisted",
    brand_name: "Twin Atlantic",
    brand_type: "artist",
    owner: "Sam",
    network: "instagram",
    content_type: "reels",
    caption: "Tour rehearsals, day one.",
    permalink: "https://www.instagram.com/reel/example3/",
    thumbnail_url: null,
    published_at: "2026-07-07",
    age_days: 34,
    views: 33000,
    median_views: 10601,
    views_multiple: 3.1,
    engagement_pct: 2.4,
    skip_rate: 76.1,
    sample_size: 20,
    assisted_from: "2026-07-20",
    assist_kinds: ["meta_ads"],
    is_assisted: true,
    avg_watch_seconds: 8.9,
  },
  {
    external_id: "mock-lofi-38",
    brand_name: "Lofi Bloom",
    brand_type: "theme",
    owner: "Sam",
    network: "tiktok",
    content_type: "posts",
    caption: "rainy window + that one synth line",
    permalink: "https://www.tiktok.com/@example/video/2",
    thumbnail_url: null,
    published_at: "2026-06-11",
    age_days: 60,
    views: 1960,
    median_views: 509.5,
    views_multiple: 3.8,
    engagement_pct: 5.5,
    skip_rate: null,
    sample_size: 14,
    assisted_from: null,
    assist_kinds: null,
    is_assisted: false,
    avg_watch_seconds: null,
  },
];

export const MOCK_BRANDS: Brand[] = [
  { id: "b1", metricool_blog_id: 111, name: "Dance to the Radio", brand_type: "artist", owner: "Sam", active: true },
  { id: "b2", metricool_blog_id: 222, name: "L'objectif", brand_type: "artist", owner: "Sam", active: true },
  { id: "b3", metricool_blog_id: 333, name: "Twin Atlantic", brand_type: "artist", owner: "Sam", active: true },
  { id: "b4", metricool_blog_id: 444, name: "Lofi Bloom", brand_type: "theme", owner: "Sam", active: true },
  { id: "b5", metricool_blog_id: 555, name: "Night Drives", brand_type: "theme", owner: "Sam", active: false },
];
